### ISSUE TITLE
Large division broken

### ISSUE THREAD

**Issue by Sebastian-git** [rgroshanrg/bigint#3]
I'm trying to divide 2 large integers, but after a certain point the quotient just becomes 0. 

Ex 1:
bigint x("108165236279178312660610114131826512483935470542850824183737259708197206310322");
bigint y("10816523631251238799");
std::cout << "x / y = " << x / y << "\n";
gives 1111110100100100111001001010110100111011000110001110101000

Ex 2:
Adding just one extra integer ends up returning 0
bigint x("108165236279178312660610114131826512483935470542850824183737259708197206310322");
bigint y("108165236312512387996");
std::cout << "x / y = " << x / y << "\n";
gives 0

I've been looking for some kind of bigfloat library that could work, but haven't found any that supports division with such large integers. I'm working on an Elliptic Curve Cryptography implementation and need to divide two large integers (both the same size as x, but y around one digit shorter) for elliptic curve division. If anyone knows any libraries that support the division, I'd appreciate it a lot.

Thanks.

**Comment by rgroshanrg** [comment]
Thanks @Sebastian-git for informing me about this bug. 
I have fixed the divide function, please take a look.

Bigfloat : http://burtleburtle.net/bob/math/bigfloat.html
Check if it works.

**Comment by Sebastian-git** [comment]
Thank you so much! It works perfectly now, I really appreciate it. I tried using Bigfloat but it didn't work out, this library is definitely a lot better for what I'm trying to make so I really appreciate the fix! I'll make sure to give full credit in my future readme.
